# Configuration du gestionnaire de secrets IRIS

# Configuration Vault
vault:
  address: "http://localhost:8200"
  token: "votre_token_vault"  # À changer en production
  mount_point: "secret"
  kv_version: 2
  tls_verify: true
  timeout: 30

# Configuration 2FA
2fa:
  secret: "votre_secret_2fa"  # À changer en production
  issuer: "IRIS"
  algorithm: "SHA1"
  digits: 6
  interval: 30
  sms_enabled: true
  twilio_sid: "votre_sid_twilio"
  twilio_token: "votre_token_twilio"
  twilio_phone: "+1234567890"

# Configuration des backups
backup:
  s3_enabled: true
  s3_bucket: "iris-secrets-backup"
  aws_access_key: "votre_access_key"
  aws_secret_key: "votre_secret_key"
  aws_region: "eu-west-1"
  backup_interval_hours: 24
  retention_days: 90
  encryption_enabled: true
  encryption_key: "votre_clé_de_chiffrement"

# Configuration du monitoring
monitoring:
  aws_access_key: "votre_access_key"
  aws_secret_key: "votre_secret_key"
  aws_region: "eu-west-1"
  metrics_interval_seconds: 60
  alert_threshold:
    failed_attempts: 5
    access_frequency: 100
  notification_channels:
    - email
    - slack
    - pagerduty

# Chemins des secrets
secrets:
  paths:
    - "auth/jwt"
    - "auth/2fa"
    - "database/credentials"
    - "api/keys"
    - "ssl/certificates"
    - "backup/keys"
    - "monitoring/credentials"

# Configuration de la rotation des secrets
rotation:
  enabled: true
  interval_days: 30
  grace_period_hours: 24
  notification_before_days: 7
  auto_rotation: true
  manual_approval: false

# Configuration des notifications
notifications:
  email:
    enabled: true
    smtp_server: "smtp.example.com"
    smtp_port: 587
    smtp_username: "security@example.com"
    smtp_password: "votre_mot_de_passe"
    from_address: "security@example.com"
    to_addresses:
      - "admin@example.com"
      - "security@example.com"
  slack:
    enabled: true
    webhook_url: "https://hooks.slack.com/services/xxx/yyy/zzz"
    channel: "#security-alerts"
  pagerduty:
    enabled: false
    api_key: "votre_clé_api"
    service_key: "votre_clé_service"

# Configuration de l'audit
audit:
  enabled: true
  log_path: "/var/log/iris/audit.log"
  max_log_size: 100MB
  backup_count: 5
  log_level: "INFO"
  events:
    - "secret_access"
    - "secret_rotation"
    - "backup_creation"
    - "2fa_setup"
    - "2fa_verification"
    - "admin_actions"

# Configuration de la sécurité
security:
  min_password_length: 12
  password_requirements:
    - uppercase
    - lowercase
    - numbers
    - special_chars
  max_login_attempts: 5
  lockout_duration_minutes: 30
  session_timeout_minutes: 60
  ip_whitelist:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
  ssl_required: true
  tls_version: "TLSv1.2"
  allowed_ciphers:
    - "ECDHE-ECDSA-AES256-GCM-SHA384"
    - "ECDHE-RSA-AES256-GCM-SHA384"
    - "ECDHE-ECDSA-CHACHA20-POLY1305"
    - "ECDHE-RSA-CHACHA20-POLY1305" 