# Configuration de sécurité IRIS

# Paramètres de cryptographie
crypto:
  master_key: "votre_clé_maîtresse_secrète"  # À changer en production
  key_rotation_days: 30
  encryption_algorithm: "AES-256-GCM"
  hash_algorithm: "SHA-256"

# Paramètres d'authentification
auth:
  jwt_secret: "votre_secret_jwt"  # À changer en production
  token_expiry_hours: 24
  password_min_length: 12
  password_requirements:
    - uppercase
    - lowercase
    - numbers
    - special_chars
  max_login_attempts: 5
  lockout_duration_minutes: 30
  session_timeout_minutes: 60

# Configuration du pare-feu
firewall:
  enabled: true
  allowed_ips:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
  blocked_ips:
    - "0.0.0.0/32"
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10

# Paramètres de sécurité réseau
network:
  ssl_enabled: true
  min_tls_version: "TLSv1.2"
  allowed_ciphers:
    - "ECDHE-ECDSA-AES256-GCM-SHA384"
    - "ECDHE-RSA-AES256-GCM-SHA384"
    - "ECDHE-ECDSA-CHACHA20-POLY1305"
    - "ECDHE-RSA-CHACHA20-POLY1305"
  hsts_enabled: true
  hsts_max_age: 31536000
  xss_protection: true
  content_security_policy: true

# Paramètres de journalisation
logging:
  security_log_path: "/var/log/iris/security.log"
  max_log_size: 100MB
  backup_count: 5
  log_level: "INFO"
  sensitive_data_masking: true
  audit_logging: true

# Paramètres de notification
notifications:
  email:
    enabled: true
    smtp_server: "smtp.example.com"
    smtp_port: 587
    smtp_username: "security@example.com"
    smtp_password: "votre_mot_de_passe"  # À changer en production
    from_address: "security@example.com"
    to_addresses:
      - "admin@example.com"
      - "security@example.com"
  slack:
    enabled: true
    webhook_url: "https://hooks.slack.com/services/xxx/yyy/zzz"
    channel: "#security-alerts"
  pagerduty:
    enabled: false
    api_key: "votre_clé_api"
    service_key: "votre_clé_service"

# Paramètres de validation des entrées
input_validation:
  enabled: true
  patterns:
    username: "^[a-zA-Z0-9_-]{3,32}$"
    email: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
    ip_address: "^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$"
    url: "^https?://[\\w\\-]+(\\.[\\w\\-]+)+[/#?]?.*$"
  max_input_length: 1000
  sanitize_output: true

# Paramètres de sécurité des fichiers
file_security:
  allowed_extensions:
    - "txt"
    - "pdf"
    - "doc"
    - "docx"
    - "xls"
    - "xlsx"
  max_file_size: 10485760  # 10MB
  scan_uploads: true
  quarantine_suspicious: true
  virus_scan: true

# Paramètres de sécurité des API
api_security:
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_size: 20
  authentication:
    required: true
    methods:
      - "api_key"
      - "jwt"
      - "oauth2"
  cors:
    enabled: true
    allowed_origins:
      - "https://example.com"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
    max_age: 3600

# Paramètres de sécurité des bases de données
database_security:
  connection_encryption: true
  password_encryption: true
  query_parameterization: true
  max_connections: 100
  connection_timeout: 30
  ssl_required: true

# Paramètres de sécurité des conteneurs
container_security:
  enabled: true
  read_only_root: true
  no_new_privileges: true
  capabilities:
    - "NET_BIND_SERVICE"
  seccomp_profile: "default"
  apparmor_profile: "default"
  resource_limits:
    memory: "512M"
    cpu: "0.5"
    pids: 100

# Paramètres de sécurité des secrets
secrets:
  vault_enabled: true
  vault_address: "http://localhost:8200"
  vault_token: "votre_token_vault"  # À changer en production
  rotation_interval_days: 30
  encryption_key_path: "/etc/iris/keys"
  backup_enabled: true
  backup_path: "/var/backup/iris/secrets" 